"use client";

import { ArrowLeftRight, FileText, Sparkles, Wand2 } from "lucide-react";
import type { useTranslations } from "next-intl";
import { useId } from "react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Props = {
	voiceDesignPrompt: string;
	setVoiceDesignPrompt: React.Dispatch<React.SetStateAction<string>>;
	t: ReturnType<typeof useTranslations>;
	text?: string;
	setText?: (value: string) => void;
	getMaxChars?: () => number;
	estimatedPoints?: number;
	tagSynced: boolean;
	onSyncFromTags: () => void;
	onManualEdit: () => void;
};

export function VoiceDesign({
	voiceDesignPrompt,
	setVoiceDesignPrompt,
	t,
	text = "",
	setText,
	getMaxChars,
	estimatedPoints = 0,
	tagSynced,
	onSyncFromTags,
	onManualEdit,
}: Props) {
	const maxChars = getMaxChars ? getMaxChars() : 500;
	const totalText = text + voiceDesignPrompt;
	const voiceDesignTextId = useId();
	const voiceDesignId = useId();
	const totalChars = totalText.length;
	const totalPoints = estimatedPoints;

	const isAutoGenerated = tagSynced && voiceDesignPrompt.trim().length > 0;

	return (
		<div className="grid grid-cols-1 lg:grid-cols-5 gap-4 min-h-[50vh]">
			{/* 左栏：合成文本输入（3/5） */}
			{setText && (
				<div className="col-span-1 lg:col-span-3 space-y-3 flex flex-col min-h-0">
					<Label
						htmlFor={voiceDesignTextId}
						className="flex items-center gap-3 text-sm font-bold shrink-0"
					>
						<div className="flex items-center justify-center w-8 h-8 rounded-xl bg-gradient-to-br from-violet-500 to-purple-600 text-white shadow-lg shadow-violet-300/50 dark:shadow-violet-900/30">
							<FileText className="h-4 w-4" />
						</div>
						<div>
							<span className="block text-violet-700 dark:text-violet-300">{t("input.label")}</span>
							<span className="text-[11px] text-violet-500/70 dark:text-violet-400/70 font-normal">
								{t("input.hint")}
							</span>
						</div>
					</Label>
					<Textarea
						id={voiceDesignTextId}
						placeholder={t("input.placeholder")}
						value={text}
						onChange={(e) => setText(e.target.value)}
						dir="auto"
						className="resize-none text-base flex-1 min-h-[25vh] sm:min-h-[35vh] border-2 border-violet-200 dark:border-violet-800/50 focus:border-violet-400 focus:ring-4 focus:ring-violet-100/50 dark:focus:ring-violet-900/30 rounded-2xl bg-gradient-to-br from-white/90 to-violet-50/30 dark:from-gray-900/90 dark:to-violet-900/20 shadow-sm hover:shadow-md transition-all duration-300 input-focus-glow overflow-y-auto"
					/>
					<div className="flex items-center justify-between shrink-0 p-2 rounded-xl bg-violet-50/50 dark:bg-violet-900/20 border border-violet-100/50 dark:border-violet-800/30">
						<span className="text-xs text-violet-600/70 dark:text-violet-400/70">
							{t("preview.hint")}
						</span>
						<span
							className={`text-xs font-medium ${totalChars > maxChars ? "text-red-500" : "text-violet-600/70 dark:text-violet-400/70"}`}
						>
							{t("input.total")} {totalChars} / {maxChars}
							{totalChars > 0 && (
								<span className="ml-2 text-violet-500 dark:text-violet-400 bg-violet-100/50 dark:bg-violet-900/50 px-1.5 py-0.5 rounded">
									≈ {totalPoints} {t("input.points")}
								</span>
							)}
						</span>
					</div>
				</div>
			)}

			{/* 右栏：音色描述输入（2/5） */}
			<div className="col-span-1 lg:col-span-2 space-y-3 flex flex-col min-h-0">
				<Label
					htmlFor={voiceDesignId}
					className="flex items-center gap-3 text-sm font-bold shrink-0"
				>
					<div className="flex items-center justify-center w-8 h-8 rounded-xl bg-gradient-to-br from-purple-500 to-fuchsia-600 text-white shadow-lg shadow-purple-300/50 dark:shadow-purple-900/30">
						<Wand2 className="h-4 w-4" />
					</div>
					<div>
						<span className="text-purple-700 dark:text-purple-300">{t("voiceDesign.label")}</span>
						{isAutoGenerated && (
							<span className="ml-2 inline-flex items-center gap-1 text-[10px] text-purple-500 bg-purple-100 dark:bg-purple-900/40 px-1.5 py-0.5 rounded-full">
								<Sparkles className="h-2.5 w-2.5" />
								{t("voiceDesign.autoGenerated")}
							</span>
						)}
					</div>
				</Label>
				<Textarea
					id={voiceDesignId}
					placeholder={t("voiceDesign.placeholder")}
					value={voiceDesignPrompt}
					onChange={(e) => {
						setVoiceDesignPrompt(e.target.value);
						onManualEdit();
					}}
					className="resize-none text-base flex-1 min-h-[25vh] sm:min-h-[35vh] border-2 border-purple-200 dark:border-purple-800/50 focus:border-purple-400 focus:ring-4 focus:ring-purple-100/50 dark:focus:ring-purple-900/30 rounded-2xl bg-gradient-to-br from-white/90 to-purple-50/30 dark:from-gray-900/90 dark:to-purple-900/20 shadow-sm hover:shadow-md transition-all duration-300 input-focus-glow overflow-y-auto"
				/>
				<div className="flex items-center gap-2 shrink-0">
					<div className="flex-1 h-1 rounded-full bg-gradient-to-r from-violet-200 to-purple-200 dark:from-violet-800 dark:to-purple-800 overflow-hidden">
						<div
							className="h-full bg-gradient-to-r from-violet-500 to-purple-500 rounded-full transition-all duration-300"
							style={{ width: `${Math.min((voiceDesignPrompt.length / 200) * 100, 100)}%` }}
						/>
					</div>
					<span className="text-xs text-muted-foreground/50">{voiceDesignPrompt.length}/200</span>
				</div>
				<div className="flex items-center justify-between shrink-0">
					<span className="text-[11px] text-muted-foreground/60">
						{isAutoGenerated
							? t("voiceDesign.syncedHint")
							: voiceDesignPrompt.trim()
								? t("voiceDesign.manualHint")
								: t("voiceDesign.guideHint")}
					</span>
					{!tagSynced && voiceDesignPrompt.trim() && (
						<Button
							variant="ghost"
							size="sm"
							className="h-6 px-2 text-[11px] text-purple-500 hover:text-purple-700 hover:bg-purple-50 dark:hover:bg-purple-900/30 gap-1"
							onClick={onSyncFromTags}
						>
							<ArrowLeftRight className="h-3 w-3" />
							{t("voiceDesign.syncFromTags")}
						</Button>
					)}
				</div>
			</div>
		</div>
	);
}
